name: "gradle-simple "
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: gradle/wrapper-validation-action@v1
      
      - name: Build and Push Docker Image
      - uses: mr-smithers-excellent/docker-build-push@v4
        with:
        image: rahilh/gradle-simple
        registry: docker.io
       
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
